// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let _supabase: any;

if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  _supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
} else {
  // Fallback no-op client to avoid app crash when env vars are missing.
  // This allows the app to run locally without supabase, but some features
  // depending on Supabase will be no-ops.
  // Prefer setting VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY) in .env.
  console.warn('VITE_SUPABASE_URL or SUPABASE anon/publishable key missing — using fallback supabase stub.');

  const noop = {
    auth: {
      onAuthStateChange: (_cb: any) => ({ data: { subscription: { unsubscribe: () => {} } } }),
      getSession: async () => ({ data: { session: null } }),
      signOut: async () => ({ error: null }),
    },
    from: (_: string) => ({
      select: async () => ({ data: null }),
      maybeSingle: async () => ({ data: null }),
      eq: () => ({ select: async () => ({ data: null }) }),
    }),
    rpc: async () => ({ data: null }),
  };

  _supabase = noop;
}

export const supabase = _supabase as any;